### PR TITLE
add support of linux arm64

### PR DESCRIPTION
**Pull request by sam0delkin**

### CODE REVIEW

**Comment by shenwei356** [comment]
Thanks

**Comment by sam0delkin** [comment]
@shenwei356 could you, please, do a release with arm linux binary?

**Comment by shenwei356** [comment]
use this first.

[rush_linux_arm64.tar.gz](https://github.com/shenwei356/rush/files/6408882/rush_linux_arm64.tar.gz)

**Comment by sam0delkin** [comment]
Thanks!

**Pull request merged**
